cart/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
  path('add/<int:product_id>/', views.add_cart, name="add_cart"),
  path('', views.cart_detail, name="cart_detail"),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
  path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

e_commerce_cbd/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"), 
    path('shop/',include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signUpView, name="signup"),
    path('account/login/', views.signInView, name="signin"),
    path('account/logout/', views.signOutView, name="signout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
   path('', views.searchResult, name="searchResult"),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
  path('',views.allProductCategory, name="allProductCategory"),
  path('<slug:c_slug>/', views.allProductCategory, name="products_by_category"),
  path('<slug:c_slug>/<slug:product_slug>/',views.ProductCategoryDetail, name="ProductCategoryDetail"),
]

templates/partials/_alerts.html
{%if messages %}
{% for message in messages %}
<div id="message" class="container">
  <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
    <button class="close" type="button" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    <strong>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      Error:
      {% else %}
      {{ message.tags | title }}
      {% endif %}
    </strong>
    {{ message }}
  </div>
</div>
{% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 text-white text-center" style="background-color: rgb(36, 196, 148);">
  Copyright &copy;
  <span class="year"></span> The Hemp Reserve
</footer>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light"> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"> 
      <li class="nav-item dropdown {% if 'shop' in request.path %} active {%endif%}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProductCategory' %}">All Products</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="GET">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
    <ul class="navbar-nav">
      {% if request.user.is_authenticated and request.user.first_name %}
        <li style="margin-left: 20px;">
          Hi, {{ request.user.first_name }} <i class="fas fa-user-circle"></i>
        </li>
        <li style="margin-left: 20px;">
          <a href="{% url 'signout' %}"> Logout <i class="fas fa-sign-out-alt"></i></a>
        </li>
      {% else %}
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'signin' %}" id="navbarDropdown" role="button"
            aria-haspopup="true" aria-expanded="false">
            Login <i class="fas fa-user-circle"></i>
          </a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'signup' %}" id="navbarDropdown" role="button"
            aria-haspopup="true" aria-expanded="false">
            Sing Up <i class="fas fa-sign-out-alt"></i>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>